# @format

version: "3.3"

services:
  node:
    image: node
    restart: always
    working_dir: /code
    ports:
      - 3333:3333
    environment:
      - SECRET=todoCarnavelTemSeuFim2001
      - MQTT_SECRET=eDeLagrima2005
      - MAX_TOKEN_TIME=1000
      - DATABASE_URL=mysql://petzeira_user:deOndeVemACalma2003@db:3306/petzeira
      - PORT=3333
      - ENV=DEV
    networks:
      - petzeira-network
    volumes:
      - ./:/code
    command: sh -c "npm install && npx prisma db push --accept-data-loss && npm start"
    depends_on:
      - "db"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petzeira
      MYSQL_USER: petzeira_user
      MYSQL_PASSWORD: deOndeVemACalma2003
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - petzeira-network
    volumes:
      - ./petzeira-mysql:/var/lib/mysql

  # db-admin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   networks:
  #     - petzeira-network

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
        - 1883:1883
        - 8883:8883
        - 9001:9001
    volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
    networks:
        - petzeira-network

networks:
  petzeira-network:
